export const FETCHING_INPROGRESS = 'FETCHING_INPROGRESS';
export const FETCHING_FAILURE = 'FETCHING_FAILURE';
// export const GET_DISEASE_AND_PESTS_DETAILS_SUCCESS =
//   'GET_DISEASE_AND_PESTS_DETAILS_SUCCESS';
export const GET_PESTS_NEWS = 'GET_PESTS_NEWS';
export const GET_STRAWBERRY_VEG_NEWS = 'GET_STRAWBERRY_VEG_NEWS';
export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_CROP_DETAILS = 'GET_CROP_DETAILS';
